export const HR_LOGIN_REQUEST = 'HR_LOGIN_REQUEST'
export const HR_LOGIN_SUCCESS = 'HR_LOGIN_SUCCESS'
export const HR_LOGIN_FAIL = 'HR_LOGIN_FAIL'
export const HR_LOGOUT = "HR_LOGOUT"

export const EMPLOYEE_LOGIN_REQUEST = 'EMPLOYEE_LOGIN_REQUEST'
export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS'
export const EMPLOYEE_LOGIN_FAIL = 'EMPLOYEE_LOGIN_FAIL'
export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT"


export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST'
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL'

export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAIL = 'INVITE_FAIL'

export const EMPLOYEE_VERIFICATION_REQUEST = 'EMPLOYEE_VERIFICATION_REQUEST'
export const EMPLOYEE_VERIFICATION_SUCCESS = 'EMPLOYEE_VERIFICATION_SUCCESS'
export const EMPLOYEE_VERIFICATION_FAIL = 'EMPLOYEE_VERIFICATION_FAIL'

export const EMPLOYEE_REGISTER_REQUEST = 'EMPLOYEE_REGISTER_REQUEST'
export const EMPLOYEE_REGISTER_SUCCESS = 'EMPLOYEE_REGISTER_SUCCESS'
export const EMPLOYEE_REGISTER_FAIL = 'EMPLOYEE_REGISTER_FAIL'
